name: Update readme

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'

      - name: Build and run C# script
        run: |
          cd Scripts
          dotnet new console --force
          dotnet add package System.Drawing.Common --version 7.0.0
          dotnet run

      - name: Update readme
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ../output.png
          git commit -m "Updated output.png"
          git push

      - name: Update README
        run: |
          sed -i 's|!\[GitHub Readme Terminal\](.*)|![GitHub Readme Terminal](./output.png)|' ../README.md
          git add ../README.md
          git commit -m "Updated README with new output image"
          git push
