name: Update readme

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x' # Use the required .NET version

      - name: Build and run C# script
        run: |
          dotnet new console -o app -n GifUpdate
          mv Scripts/Program.cs app/Program.cs
          dotnet run --project app

      - name: Update readme
        run: |
          branch_name="gifos"

          if git rev-parse --verify --quiet "$branch_name"; then
              git branch -D "$branch_name"
          fi

          git checkout --orphan "$branch_name"
          git rm -rf .
          git add output.png
          git -c "user.name=bot" -c "user.email=bot@github.com" commit -m "Automatically updated on $(date)"
          git push -u -f origin $branch_name
