name: Update readme with GIF

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install pillow imageio

      - name: Generate GIF
        run: |
          cd Scripts
          python generate_gif.py
          mv output.gif ../output.gif

      - name: Update readme
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ../output.gif
          git commit -m "Updated output.gif"
          git push

      - name: Update README
        run: |
          sed -i 's|!\[GitHub Readme Terminal\](.*)|![GitHub Readme Terminal](./output.gif)|' ../README.md
          git add ../README.md
          git commit -m "Updated README with new output GIF"
          git push
